=== Energinet-DataHub/Green-Energy-Hub/src/schemas/source/GreenEnergyHub.Schemas.Json/Schemas/ChangeOfSupplier.schema.json
{
    "$id": "https://github.com/green-energy-hub/schemas/change-of-supplier",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Change of supplier",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "BalanceResponsibleParty": { "$ref": "https://github.com/green-energy-hub/schemas#/definitions/marketParticipant" },
        "EnergySupplier": { "$ref": "https://github.com/green-energy-hub/schemas#/definitions/marketParticipant"},
        "Consumer": { "$ref": "https://github.com/green-energy-hub/schemas#/definitions/marketParticipant"},
        "MarketEvaluationPoint": { "$ref": "https://github.com/green-energy-hub/schemas#/definitions/marketEvaluationPoint" },
        "StartDate": { 
            "title": "Start of occurrence",
            "description": "Date in UTC that defines the date when a new energysupplier is responsible for the meteringpoint",
            "$ref": "https://github.com/green-energy-hub/schemas#/definitions/utc_date" 
        },
        "Transaction": { "$ref": "https://github.com/green-energy-hub/schemas#/definitions/referenceId" }
    },
    "required": [ "BalanceResponsibleParty", "EnergySupplier", "Consumer", "MarketEvaluationPoint", "StartDate", "Transaction" ]
}

=== Energinet-DataHub/Green-Energy-Hub/src/schemas/source/GreenEnergyHub.Schemas.Json.Tests/TestData/ChangeOfSupplierValid.json
{
  "BalanceResponsibleParty": {
    "mRID": {
      "value": "12345678",
      "qualifier": "VA"
    }
  },
  "EnergySupplier": {
    "mRID": {
      "value": "12345678",
      "qualifier": "VA"
    }
  },
  "Consumer": {
    "mRID": {
      "value": "1234567890",
      "qualifier": "ARR"
    },
    "name": "Hans Hansen"
  },
  "MarketEvaluationPoint": {
    "mRID": "123456789123456789"
  },
  "StartDate": "2020-10-10T20:00:00.000Z",
  "Transaction": {
    "mRID": "a01dbf8b-ea99-4798-9bd4-ed85ecf79897"
  }
}
